source 'https://supermarket.chef.io'

cookbook 'apache2', '~> 3.2.2'

# The HAProxy cookbook does not properly read the ip address of the nodes
# in some clouds. This branch contains a temporal patch that can be used until
# the bug is fixed. See: https://github.com/hw-cookbooks/haproxy/pull/130 
cookbook 'haproxy', git: 'https://github.com/nacx/haproxy', branch: 'jclouds'
